### ISSUE TITLE
result problem

### ISSUE THREAD

**Issue by jiejiangtao** [AlexanderKroll/KM_prediction_function#3]
Hello, I used the 274 test sets in the sabio database mentioned in your paper"Deep learning allows genome-scale prediction of Michaelis constants from structural features"。sing the model provided here, and the results were：'pearson': tensor(0.6948), 'rmse': tensor(0.8430), 'r2': tensor(0.4667)
Is the result due to a difference in the use of the model, or is it due to a problem with the input? Here is the input code：

import pandas as pd
compare_df = pd.read_csv('sabio_df_checkpoint3_V2.csv', index_col=False)
subs = []
sequs = []
for ind in compare_df.index:
    subs.append(compare_df['KEGG ID'][ind])
    sequs.append(compare_df['Sequence'][ind])
KM = KM_predicton(substrate_list=subs, enzyme_list=sequs)
KM.to_csv('test1.csv')

**Comment by jiejiangtao** [comment]
Thanks

**Comment by AlexanderKroll** [comment]
Dear jiejiangtao,

to me it looks like you have done everything right. The test metrics that you achieved are very similar to the ones that we  achieved in the manuscript: (R2: 0.47 vs. 0.49) and (MSE: 0.71 vs. 0.67). This indicates that you produce meaningful results. Please note that the prediction function in this repository is not completely identical to the function from our manuscript or the following GitHub repository: https://github.com/AlexanderKroll/KM_prediction

I stated the reason for that in the Readme of this repository:
"Please note that the provided model is not identical to the one presented in the paper: Here, we used enzyme representations that are slightly different. Instead of the UniRep model, here we are using the ESM-1b model to create the enzyme representations. It was shown that the ESM-1b model outperforms the UniRep model as it is trained with a more up-to-date model for natural language processing (with a transformer network instead of a LSTM)."
